name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${EC2_KEY}" > moodtune-keypair.pem
          chmod 600 moodtune-keypair.pem

          # Transfer files to EC2
          scp -o StrictHostKeyChecking=no -i moodtune-keypair.pem -r ./aws $EC2_USER@$EC2_HOST:/home/ec2-user/app

          # SSH into EC2 and restart the service
          ssh -o StrictHostKeyChecking=no -i moodtune-keypair.pem $EC2_USER@$EC2_HOST << EOF
            sudo systemctl restart fastapi
          EOF
