name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          # SSH 키 파일의 권한 설정 (이미 존재하는 경우)
          chmod 600 /Users/zziglet/aws/moodtune-keypair.pem

          # EC2로 파일 전송
          scp -o StrictHostKeyChecking=no -i "/Users/zziglet/aws/moodtune-keypair.pem" -r /Users/zziglet/aws $EC2_USER@$EC2_HOST:/home/***/app

          # EC2에 접속하여 서비스 재시작
          ssh -o StrictHostKeyChecking=no -i "/Users/zziglet/aws/moodtune-keypair.pem" $EC2_USER@$EC2_HOST << EOF
            sudo systemctl restart fastapi
          EOF
